#import "./fieldsFragment.gql"
mutation createProduct ($object:products_insert_input!,$on_conflict:products_on_conflict){
    insert_products_one(object:$object, on_conflict:$on_conflict){
        ...Fields
    }
}