#import "../commonFieldsFragment.gql"
#import "../categories/fieldsFragment.gql"
fragment Fields on products {
    id
    created_at
    updated_at
    stock
    sku
    description
    featured
    categories{
      category{
        ...CategoryFiels
      }
    }
    images{
      type
      image{
        ...ImageFields
      }
    }
    name
    saved_price
    final_price
    price
    discount_percentage
    
}