fragment usersFields on users{
    id
    name
    email
    mobile_number
    roles{
        role{
            name
            permissions{
                permission
            }              
        }
    }
    created_at
    updated_at
}