fragment usersFields on users{
    id
    name
    email
    mobile_number
    active_orders_assigned:assigned_orders(where:{
       order:{
        order_status:{
          value:{_neq:"completed"}
        }
      }
    }){
      __typename
    }
    roles{
        role{
            name
            permissions{
                permission
            }              
        }
    }
    created_at
    updated_at
}