#import "./fieldsFragment.gql"
mutation delete_categories ($where:categories_bool_exp!){
    delete_categories(where:$where){
         ...CategoryFiels
        sub_categories{
            child{
                ...CategoryFiels
            }
        }
    }
}