#import "./fieldsFragment.gql"
query category($id:uuid!){
    categories_by_pk(id:$id){
        ...CategoryFiels
        sub_categories{
            child{
                ...CategoryFiels
            }
        }
    }
}