#import "./fieldsFragment.gql"
mutation updateCategrory ($pk_columns:categories_pk_columns_input!, $_set:categories_set_input){
    update_categories_by_pk(pk_columns:$pk_columns, _set:$_set){
        ...CategoryFiels
    }
}