query role_and_permissions ($order_by:[roles_order_by!], $limit:Int,$offset:Int,$where:roles_bool_exp){
  roles(order_by:$order_by, limit:$limit,offset:$offset,where:$where){
    id
    name
    permissions{
      permission
    }
  }
}