#import "./fieldsFragment.gql"
query orders($limit:Int,$offset:Int,$where:orders_bool_exp,$order_by:[orders_order_by!]){
    orders_aggregate( where:$where){
        aggregate{
            count
        }
    }
    orders(limit:$limit, offset:$offset, where:$where,order_by:$order_by){
        ...orderFields
    }
}