#import "../users/fieldsFragment.gql"
#import "../addresses/fieldsFragment.gql"
fragment orderFields on orders {
    id
    track_id
    assigned_driver{
        driver{
          name
          id
        }
    }
    order_status{
      value
      status
    }
    status
    way
    delivery_way{
      cost
    }
    notes
    address{
      ...addressFields
    }
    client{
      name
      id
    }
    selected_products{
      quantity
      calculated_quantity_times_cost
    }
    options{
      deletable
      modifiable
    }
    created_at
    updated_at    
}